# Generated by Django 3.2 on 2024-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreBookingDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_work_day',
            field=models.DateField(default='2024-10-24'),
            preserve_default=False,
        ),
    ]
