# Generated by Django 3.2.25 on 2024-10-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
