# Generated by Django 3.2.25 on 2024-10-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerBooking', '0003_alter_customerbooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customerbooking',
            name='technician',
        ),
    ]
