# Generated by Django 3.2.25 on 2024-10-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerBooking', '0004_auto_20241007_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
