# Generated by Django 3.2.25 on 2024-10-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerBooking', '0005_customerbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbooking',
            name='technician',
            field=models.EmailField(default='none', max_length=254, unique=True, verbose_name='Technician Mail'),
        ),
    ]
