# Generated by Django 3.2.25 on 2024-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerBooking', '0007_auto_20241007_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbooking',
            name='customer',
            field=models.EmailField(blank=True, default='none', max_length=254, verbose_name='Customer Mail'),
        ),
    ]
