# Generated by Django 3.2 on 2024-10-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerBooking', '0010_auto_20241023_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbooking',
            name='service',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
